export let swaraColorMap = new Map([
    ["SS", "dark.3"],
    ["S", "dark.3"],
    ["P", "pink.5"],
    ["R1", "pink.3"],
    ["R2", "grape.3"],
    ["R3", "violet.3"],
    ["G1", "indigo.3"],
    ["G2", "blue.3"],
    ["G3", "cyan.3"],
    ["M1", "cyan.4"],
    ["M2", "red.4"],
    ["D1", "teal.3"],
    ["D2", "green.3"],
    ["D3", "lime.3"],
    ["N1", "yellow.3"],
    ["N2", "orange.3"],
    ["N3", "orange.4"],
])

export let swaraNoteMap = new Map([
    ["S", "C4"],
    ["R1", "C#4"],
    ["R2", "D4"],
    ["R3", "D#4"],
    ["G1", "D4"],
    ["G2", "D#4"],
    ["G3", "E4"],
    ["M1", "F4"],
    ["M2", "F#4"],
    ["P", "G4"],
    ["D1", "G#4"],
    ["D2", "A4"],
    ["D3", "A#4"],
    ["N1", "A4"],
    ["N2", "A#4"],
    ["N3", "B4"],
])